### ISSUE TITLE
Disable eslint style rules and only use prettier

### ISSUE THREAD

**Issue by vincentfretin** [aframevr/aframe-inspector#642]
- [x] Disable eslint `space-before-function-paren` rule that conflicts with how prettier format the files. Done in #639
- [x] Update prettier to the latest version and run it again on all the files. Done in #647
- [x] Integrate husky to use a pre-commit hook to format the files for new contributions. Done in #647
- [x] Add Github Actions to run `npm run test:ci` `npm run dist` `npm run lint` and remove the old `.travis.yml` file. Done in #646 

This closes #581

**Comment by vincentfretin** [comment]
In #639 I disabled the space-before-function-paren eslint rule and specified the singleQuote in prettier config, so now the two tools works well together.

**Comment by vincentfretin** [comment]
Current prettier version used is 1.15.3, with newer 1.19.1, only 9 files are modified. We should at least modify those 9 files.
If we update to latest prettier 2.7.1, it will modify 33 files.
I'd really like that we update this, it will make any further contributions for me easier, when I'm comparing the files in my project to the one in this repo.

**Comment by vincentfretin** [comment]
Done in #647
